CREATE TABLE users (  id SERIAL PRIMARY KEY,  username VARCHAR(255) NOT NULL UNIQUE,  email VARCHAR(255) NOT NULL UNIQUE,  password_hash VARCHAR(255) NOT NULL,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

CREATE TABLE products (  id SERIAL PRIMARY KEY,  name VARCHAR(255) NOT NULL,  description TEXT,  price DECIMAL(10, 2) NOT NULL,  stock_quantity INT DEFAULT 0,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

CREATE TABLE carts (  id SERIAL PRIMARY KEY,  user_id INT REFERENCES users(id),  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

CREATE TABLE cart_items (  id SERIAL PRIMARY KEY,  cart_id INT REFERENCES carts(id),  product_id INT REFERENCES products(id),  quantity INT DEFAULT 1,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

CREATE TABLE orders (  id SERIAL PRIMARY KEY,  user_id INT REFERENCES users(id),  total DECIMAL(10, 2) NOT NULL,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

CREATE TABLE order_items (  id SERIAL PRIMARY KEY,  order_id INT REFERENCES orders(id),  product_id INT REFERENCES products(id),  quantity INT NOT NULL,  price DECIMAL(10, 2) NOT NULL,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

CREATE TABLE payment_methods (  id SERIAL PRIMARY KEY,  user_id INT REFERENCES users(id),  card_type VARCHAR(50),  card_number VARCHAR(20),  expiration_date DATE,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE addresses (  id SERIAL PRIMARY KEY,  user_id INT REFERENCES users(id),  address_line1 VARCHAR(255) NOT NULL,  address_line2 VARCHAR(255),  city VARCHAR(100) NOT NULL,  state VARCHAR(100) NOT NULL,  postal_code VARCHAR(20) NOT NULL,  country VARCHAR(100) NOT NULL,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE notifications (  id SERIAL PRIMARY KEY,  user_id INT REFERENCES users(id),  message TEXT NOT NULL,  is_read BOOLEAN DEFAULT FALSE,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);